apiVersion: apps/v1
kind: Deployment
metadata:
 name: cerner-deploy
spec:
 selector:
   matchLabels:
     app: cerner-app
 replicas: 1
 template:
   metadata:
     labels:
       app: cerner-app
   spec:
     containers:
     - name: cerner-kube
   # enter the path to your image, be sure to include the correct region prefix
       image: iad.ocir.io/gse00014942/cerner/api:ocir
       imagePullPolicy: Always
       ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 name: cerner-service
spec:
 type: LoadBalancer
 ports:
 - port: 80
   protocol: TCP
   targetPort: 3000
 selector:
   app: cerner-app