apiVersion: apps/v1
kind: Deployment
metadata:
 name: dep-cerner
spec:
 selector:
   matchLabels:
     app: cerner
 replicas: 1
 template:
   metadata:
     labels:
       app: cerner
   spec:
     containers:
     - name: c-kube
   # enter the path to your image, be sure to include the correct region prefix
       image: ${DOCKER_REPO}:${DOCKER_TAG}
       imagePullPolicy: Always
       ports:
       - containerPort: ${PORT}
---
apiVersion: v1
kind: Service
metadata:
 name: serve-cerner
spec:
 type: LoadBalancer
 ports:
 - port: 80
   protocol: TCP
   targetPort: ${PORT}
 selector:
   app: cerner